In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
my_arr=np.arange(10)
print(my_arr)
print(type(my_arr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
my_list=list(range(10))
print(my_list)
print(type(my_list))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [ ]:
import sys
s=range(1000)
print("Size of each element of list in bytes:",sys.getsizeof(s))
print("Size of the whole list in bytes:",sys.getsizeof(s)*len(s))

d=np.arange(1000)
print("Size of each element of list in bytes:",d.itemsize)
print("Size of the whole list in bytes:",d.size*d.itemsize)


Size of each element of list in bytes: 48
Size of the whole list in bytes: 48000
Size of each element of list in bytes: 8
Size of the whole list in bytes: 8000


In [ ]:
print(type(s))

<class 'range'>


In [ ]:
arr=np.array(42)
print(arr)

42


In [ ]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
a=np.array(5)
print(a.ndim)
b=np.array([1,2,3,4,5])
print(b.ndim)
c=np.array([[1,2,3],[4,5,6]])
print(c.ndim)

0
1
2


In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [ ]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
print("Shape= ",data.shape)
print("Type= ",data.dtype)
print("Data = ", data)
print("\nAns1 = ",data * 10)
print("\nAns2= ",data+data)

Shape=  (2, 3)
Type=  float64
Data =  [[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]

Ans1 =  [[ 15.  -1.  30.]
 [  0. -30.  65.]]

Ans2=  [[ 3.  -0.2  6. ]
 [ 0.  -6.  13. ]]


In [ ]:
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list)
print(type(arr))
print(arr)
print("\n", arr.dtype)

<class 'numpy.ndarray'>
[1 2 3 4 5]

 int64


In [ ]:
zeros_arr = np.zeros((5,2))
eros_arr = np.zeros(5)
print(zeros_arr)

zeros_arr = np.zeros((2,3))
print(zeros_arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones_arr = np.ones(6)
print(ones_arr)
ones_arr = np.ones((3,2,4))
print("\n",ones_arr)
print("\n ndim= ",ones_arr.ndim)
print("\nData type of the array: ",ones_arr.dtype)
ones_arr_int = np.ones((2,2), dtype=np.int16)
print("\nArray of ones with integer elements: \n",ones_arr_int)

[1. 1. 1. 1. 1. 1.]

 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

 ndim=  3

Data type of the array:  float64

Array of ones with integer elements: 
 [[1 1]
 [1 1]]


In [ ]:
empty_arr = np.empty((3,2))
print(empty_arr)
print("\nData type of the array: ",empty_arr.dtype)

[[1. 1.]
 [1. 1.]
 [1. 1.]]

Data type of the array:  float64


In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)
identity_matrix = np.eye(4)
print("\n",identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
zero=np.zeros((3,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
zero=np.ones((3,3))
print(zero)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
zero=np.eye((3))
print(zero)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [ ]:
arr = np.array([1.1, 2.2, 3.3])
print("Before converting: ", arr, arr.dtype)
new_arr = arr.astype('i')
print("After converting: ", new_arr, new_arr.dtype)

Before converting:  [1.1 2.2 3.3] float64
After converting:  [1 2 3] int32


In [ ]:
arr = np.array(['1.1', '2.2', '-3.3'])
print("Before converting: ", arr, arr.dtype)
new_arr = arr.astype('f')
print("After converting: ", new_arr, new_arr.dtype)

Before converting:  ['1.1' '2.2' '-3.3'] <U4
After converting:  [ 1.1  2.2 -3.3] float32


In [ ]:
arr1 = np.arange(10)
arr2 = np.random.randn(10)
print("array 1\n",arr1, arr1.dtype)
print("Array 2 \n",arr2, arr2.dtype)
new_arr = arr1.astype(arr2.dtype)
print("New Array \n",new_arr, new_arr.dtype)

array 1
 [0 1 2 3 4 5 6 7 8 9] int64
Array 2 
 [-0.98355141  0.52259365  0.67554087 -0.6568855  -0.02571189  0.68800862
 -0.43361891 -0.03295461 -0.13025501 -0.84587695] float64
New Array 
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64


In [ ]:
str_arr = np.array(['hello', 'world', 'numpy'])
print(str_arr)

['hello' 'world' 'numpy']


In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[    1    64  2187 65536]


In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a+1)
print(a-1)
print(a*2)
print(a/2)
print(a**2)
print(1/a)

[2 3 4 5]
[0 1 2 3]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[1.         0.5        0.33333333 0.25      ]


In [ ]:
arr=np.arange(12)
print(arr)
print(" ")
newarr=arr.reshape(3,4)
print(newarr)
print(" ")
new_arr=arr.reshape((3,-1),order="F")
print(new_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
 
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [ ]:
a=np.array([[1,2],[3,4]])
print(a)
print(" ")
flatten_a=a.flatten()
flatten_a[0]=10
print(flatten_a)

[[1 2]
 [3 4]]
 
[10  2  3  4]


In [ ]:
a=np.array([[1,2],[3,4]])
raveled_a=a.ravel()
raveled_a[0]=10
print(raveled_a)
print(a)

[10  2  3  4]
[[10  2]
 [ 3  4]]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[2, 1], [3, 5]])
greater_than = arr1 > arr2
less_than = arr1 < arr2
equal_to = arr1 == arr2
print("Greater than:\n", greater_than)
print("\nLess than:\n", less_than)
print("\nEqual to:\n", equal_to)

Greater than:
 [[False  True]
 [False False]]

Less than:
 [[ True False]
 [False  True]]

Equal to:
 [[False False]
 [ True False]]


In [ ]:
a=np.arange(12).reshape(3,4)
b=a>4
print(b)
a[b]=10
print(a)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[[ 0  1  2  3]
 [ 4 10 10 10]
 [10 10 10 10]]


In [ ]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data=np.arange(28).reshape(7,4)
print(names)
print(data)
print(names=='Bob')
print(data[names=='Bob',2:])
print(" ")
print(data[names=='Bob',3])

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
[ True False False  True False False False]
[[ 2  3]
 [14 15]]
 
[ 3 15]


In [ ]:
arr = np.arange(32).reshape(8, 4)
print("arr= \n",arr)
print("\narr[[1, 5, 7, 2]]= \n",arr[[1, 5, 7, 2]])
print("\narr[[1, 5, 7, 2], [0, 3, 1, 2]]= \n",arr[[1, 5, 7, 2], [0, 3, 1, 2]])
arr[[1, 5, 7, 2]] = 1

arr= 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

arr[[1, 5, 7, 2]]= 
 [[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]

arr[[1, 5, 7, 2], [0, 3, 1, 2]]= 
 [ 4 23 29 10]


In [ ]:
arr = np.arange(12).reshape((3, 4))
print(arr)
print("Transpose using .T")
print(arr.T)
print("Transpose using the transpose() function")
print(np.transpose(arr))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transpose using .T
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Transpose using the transpose() function
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
arr1=np.transpose(arr,(1,0))
print(arr1)
arr2=np.transpose(arr,(0,1))
print(arr2)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
arr = np.arange(12).reshape((2, 3,2))
print(arr)
print("Transpose using .T")
arr3dT=arr.T
print(arr3dT)
print(arr3dT.shape)
print("Transpose using the transpose() function")
print(np.transpose(arr))

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
Transpose using .T
[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]
(2, 3, 2)
Transpose using the transpose() function
[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]


In [ ]:
arr = np.arange(12).reshape((3, 4))
print("Dot product of arr and arr2:")
print(np.dot(arr, arr.T))

Dot product of arr and arr2:
[[ 14  38  62]
 [ 38 126 214]
 [ 62 214 366]]


In [ ]:
arr = np.arange(12).reshape((3, 4))
print(arr)
print("Swap axes 0 and 1:")
print(np.swapaxes(arr, 0, 1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Swap axes 0 and 1:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
arr1 = np.array([[1, 2],
[3, 4]])
arr2 = np.array([[5, 6],
[7, 8]])
result = np.multiply(arr1, arr2)
print(result)

[[ 5 12]
 [21 32]]
